### ISSUE TITLE
下载demo就这样了，更新cocopods没有，求解

### ISSUE THREAD

**Issue by tiayako** [boai/BABaseProject#1]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MJRefreshHeader", referenced from:
      objc-class-ref in BABaseTableViewController.o
  "_OBJC_CLASS_$_AFNetworkActivityIndicatorManager", referenced from:
      objc-class-ref in AppDelegate+BACategory.o
      objc-class-ref in BANetManager.o
  "_OBJC_CLASS_$_MBProgressHUD", referenced from:
      objc-class-ref in NSObject+BAProgressHUD.o
  "_OBJC_CLASS_$_AFJSONResponseSerializer", referenced from:
      objc-class-ref in BANetManager.o
  "_OBJC_CLASS_$_AFHTTPSessionManager", referenced from:
      objc-class-ref in BANetManager.o
  "_OBJC_METACLASS_$_MJRefreshGifHeader", referenced from:
      _OBJC_METACLASS_$_BACustomMJHeader in BACustomMJHeader.o
  "_OBJC_CLASS_$_MJRefreshFooter", referenced from:
      objc-class-ref in BABaseTableViewController.o
  "_OBJC_CLASS_$_AFSecurityPolicy", referenced from:
      objc-class-ref in BANetManager.o
  "_OBJC_CLASS_$_IQKeyboardManager", referenced from:
      objc-class-ref in AppDelegate+BACategory.o
  "_OBJC_CLASS_$_AFNetworkReachabilityManager", referenced from:
      objc-class-ref in AppDelegate+BACategory.o
      objc-class-ref in BANetManager.o
      objc-class-ref in BABaseViewController.o
  "_OBJC_CLASS_$_MJRefreshGifHeader", referenced from:
      _OBJC_CLASS_$_BACustomMJHeader in BACustomMJHeader.o
  "_OBJC_CLASS_$_MJRefreshAutoGifFooter", referenced from:
      _OBJC_CLASS_$_BACustomMJFooter in BACustomMJFooter.o
  "_OBJC_METACLASS_$_MJRefreshAutoGifFooter", referenced from:
      _OBJC_METACLASS_$_BACustomMJFooter in BACustomMJFooter.o
  "_OBJC_CLASS_$_BACustomButton", referenced from:
      objc-class-ref in DemoVC12View.o
      objc-class-ref in DemoVC4.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by boai** [comment]
你这个应该是打开的文件不对，你看下文件夹，打开BABaseProject.xcworkspace这个文件才对！

**Comment by ghost** [comment]
What‘s your Xcode version？
