### ISSUE TITLE
info.plist权限问题

### ISSUE THREAD

**Issue by k373379320** [boai/BABaseProject#6]
在iPhone,iOS10+下;
首页->最新->8丶系统提醒和更新;出现Carsh

解决方案:
在info.plist添加

  <key>NSCalendarsUsageDescription</key>
     <string>是否允许此App使用日历？</string>
  <key>Privacy - Reminders Usage Description</key>
     <string>是否允许次App使用提醒?</string>

**Comment by boai** [comment]
此问题已修复，多谢提醒！
